{% set name = "b2sdk" %}
{% set version = "2.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/b2sdk-{{ version }}.tar.gz
  sha256: 36272796b746b66f5577192393d04430de4e5e155da3aaea341a88cb54fcd601

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - annotated-types >=0.5.0
    - importlib-metadata >=3.3.0
    - logfury <2.0.0,>=1.0.1
    - requests <3.0.0,>=2.9.1
    - typing-extensions >=4.7.1

test:
  imports:
    - b2sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Backblaze/b2-sdk-python
  summary: Backblaze B2 SDK
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - b2sdk/_internal/requests/LICENSE
    - b2sdk/_internal/requests/NOTICE

extra:
  recipe-maintainers:
    - freundTech
