{% set name = "b2sdk" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/b2sdk-{{ version }}.tar.gz
  sha256: da7b65e1af4f59c7de7d079c1e25de6b033aa45090fded4caefe52ded9b13ee6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.24.2
    - hatch-vcs >=0.4
    - pip
  run:
    - python >={{ python_min }}
    - annotated-types >=0.5.0
    - logfury <2.0.0,>=1.0.1
    - requests <3.0.0,>=2.9.1
    - typing-extensions >=4.7.1

test:
  imports:
    - b2sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Backblaze/b2-sdk-python
  summary: Backblaze B2 SDK
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - b2sdk/_internal/requests/LICENSE
    - b2sdk/_internal/requests/NOTICE

extra:
  recipe-maintainers:
    - freundTech
